import {
  route_foreroom,
  route_create_post,
  route_edit_post,
  route_view_post,
  route_create_poll,
  route_edit_poll,
  route_view_poll,
  route_family_tree_add_member,
  route_family_tree_view_member,
  route_family_tree_edit_member,
  route_login,
  route_family_tree,
  route_register,
  route_profile,
  route_chats,
  route_settings,
  route_notifications,
  route_events,
  route_kincoins,
  route_will,
} from "./routeEnpoints";

const routeTitles = {
  [route_foreroom]: "Foreroom",
  [route_create_post]: "Create Post",
  [route_edit_post]: "Edit Post",
  [route_view_post]: "View Post",
  [route_create_poll]: "Create Poll",
  [route_edit_poll]: "Edit Poll",
  [route_view_poll]: "View Poll",
  [route_family_tree_add_member]: "Add Member",
  [route_family_tree_view_member]: "View Member",
  [route_family_tree_edit_member]: "Edit Member",
  [route_login]: "Login",
  [route_family_tree]: "Family Tree",
  [route_register]: "Register",
  [route_profile]: "Profile",
  [route_chats]: "Chats",
  [route_settings]: "Settings",
  [route_notifications]: "Notifications",
  [route_events]: "Events",
  [route_kincoins]: "Kincoins",
  [route_will]: "Will",
};

export default routeTitles;
